coverage:
  status:
    project:
      default:
        target: 0%    # the required coverage value
        threshold: 100%  # the leniency in hitting the target
    patch:
      default:
        target: 0%
        threshold: 100%