repos:

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--safe, --quiet]

# Some basic Flake8
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [ '--max-line-length=88', '--select=E401,E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F405,F631,F632,F633,F811,F812,F821,F822,F841,F901,W191,W291,W292,W293,W602,W603,W604,W605,W606' ]


  # Other syntax checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=200']
