gonio:
  axes:
    - name: omega
      depends: "."
      transformation_type: rotation
      vector: [-1,0,0]
      start_pos: -90.0
    - name: kappa
      depends: omega
      transformation_type: rotation
      vector: [-0.642788, -0.766044, 0.0]
    - name: phi
      depends: kappa
      transformation_type: rotation
      vector: [-1,0,0]
      start_pos: 80.0
      increment: 0.1
      num_steps: 50
    - name: sam_z
      depends: phi
      transformation_type: translation
      vector: [0,0,1]
      start_pos: 0.120
    - name: sam_y
      depends: sam_z
      transformation_type: translation
      vector: [0,1,0]
    - name: sam_x
      depends: sam_y
      transformation_type: translation
      vector: [1,0,0]
      start_pos: 0.240
    
instrument:
  beam:
    wavelength: 0.9
  source:
    beamline: i19-2
  attenuator:
    transmission: 0.5
  
det:
  axes:
    - name: two_theta
      depends: "."
      transformation_type: rotation
      vector: [-1,0,0]
      start_pos: 0.0
    - name: det_z
      depends: two_theta
      transformation_type: translation
      vector: [0,0,1]
      start_pos: 250
  params:
    description: Eiger2 X 4M
    image_size: [2162, 2068]
    sensor_material: CdTe
    overload: 50649
    underload: -1
  beam_center: [1134, 1458]
  exposure_time: 0.01
  module:
    fast_axis: [0,1,0]
    slow_axis: [-1,0,0]

sample:
  depends: phi
  