gonio:
  axes:
    - name: omega
      depends: "."
      transformation_type: rotation
      vector: [-1,0,0]
    - name: sam_z
      depends: "omega"
      transformation_type: translation
      vector: [0,0,1]
    - name: sam_y
      depends: "sam_z"
      transformation_type: translation
      vector: [0,1,0]
    - name: sam_x
      depends: "sam_y"
      transformation_type: translation
      vector: [1,0,0]

instrument:
  beam:
    wavelength: 0.6
  source:
    beamline: "i24"
  attenuator:
    transmission: 0.3

det:
  axes:
    - name: det_z
      depends: "."
      transformation_type: translation
      vector: [0,0,1]
      start_pos: 1450.0
  params:
    description: Eiger2 X 9M
    image_size: [3262, 3108]
    sensor_material: CdTe
    overload: 65535
    underload: -1
  beam_center: [1134, 1458]
  exposure_time: 0.01
  module:
    fast_axis: [-1,0,0]
    slow_axis: [0,1,0]
