name: Code CI

on:
  push:
  pull_request:
  schedule:
    # Run weekly to check latest versions of dependencies
    - cron: "0 8 * * WED"

jobs:
  lint:
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      
      - name: Checkout nexgen
        uses: actions/checkout@v3

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          requirements_file: requirements_dev.txt
          install_options: -e .[dev]
      
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        uses: TrueBrain/actions-flake8@v2
        with:
          path: src
    
      - name: Lint
        run: tox -e pre-commit,mypy
  
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python: ["3.9", "3.10", "3.11"]
        install: ["-e .[dev]"]
        # Make one version be non-editable to test both paths of version code
        include:
          - os: "ubuntu-latest"
            python: "3.8"
            install: ".[dev]"
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          python_version: ${{ matrix.python }}
          install_options: ${{ matrix.install }}

      - name: List dependency tree
        run: pipdeptree

      - name: Run tests
        run: pytest --random-order

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.python }}/${{ matrix.os }}
          files: cov.xml